/** Name of this package. */
export const PACKAGE = "@openlfcp/wire";

export {
  type ControlBody,
  type ControlBodyType,
  type ControlRecord,
  type ControlRecordHeader,
  controlBodyFromCbor,
  controlBodyToCbor,
  controlRecordSigner,
  controlTypeOf,
  decodeControlRecord,
  encodeControlRecordPayload,
  isMvpSupported,
  type OwnerTransferAcceptPayload,
  type OwnerTransferOfferPayload,
  ownerTransferAcceptPayloadFromCbor,
  ownerTransferOfferPayloadFromCbor,
  parseOwnerTransferAccept,
  parseOwnerTransferOffer,
  type SignedControlRecord,
  signControlRecord,
  verifyGenesis,
} from "./control.js";
export {
  COSE_ALG_EDDSA,
  objectId,
  parseSignedObject,
  type SignedBytes,
  type SignedObject,
  type Signer,
  signObject,
  sigStructureBytes,
  type VerifyResult,
  verifySignedObject,
} from "./cose.js";
export {
  checkWriterUrl,
  ENDPOINT_FLAGS,
  type Endpoint,
  endpointFromCbor,
  endpointToCbor,
} from "./endpoint.js";
export {
  type ActorHave,
  actorHaveFromCbor,
  actorHaveToCbor,
  canonicalFrontierFromCbor,
  canonicalFrontierToCbor,
  type SequenceRange,
} from "./have.js";
export {
  CONTROL_TYPE,
  type ControlRecordPayload,
  controlRecordPayloadFromCbor,
  type DataUnitPayload,
  dataUnitPayloadFromCbor,
  decodeControlRecordPayload,
  decodeDataUnitPayload,
  decodeKeyPackagePayload,
  decodeSnapshotPayload,
  expectedSignerOf,
  type KeyPackagePayload,
  keyPackagePayloadFromCbor,
  type Parsed,
  parseControlRecord,
  parseDataUnit,
  parseKeyPackage,
  parseSnapshot,
  type SnapshotPayload,
  snapshotPayloadFromCbor,
} from "./objects.js";
export {
  decodePrincipalDescriptor,
  derivePrincipalId,
  encodePrincipalDescriptor,
  type PrincipalDescriptor,
  principalDescriptor,
  principalDescriptorFromCbor,
  principalDescriptorFromKeys,
  principalDescriptorToCbor,
} from "./principal.js";
