/** Name of this package. */
export const PACKAGE = "@openlfcp/wire";

export {
  ABILITY,
  ABILITY_NAMES,
  type Authorization,
  abilitiesOf,
  authorizeControlRecord,
  type CapabilityState,
  canDistributeKey,
  type Grant,
  hasAbility,
  isGrantActive,
  isStandardAbility,
  type VerifiedOwnerTransfer,
  verifyOwnerTransfer,
} from "./capability.js";
export {
  type ChainOptions,
  type ChainProblem,
  type ChainResult,
  type ControlEpoch,
  type ControlRoute,
  type ControlState,
  type EpochHistory,
  validateControlChain,
} from "./chain.js";
export {
  type ControlBody,
  type ControlBodyType,
  type ControlRecord,
  type ControlRecordHeader,
  controlBodyFromCbor,
  controlBodyToCbor,
  controlRecordSigner,
  controlTypeOf,
  decodeControlRecord,
  encodeControlRecordPayload,
  isMvpSupported,
  type OwnerTransferAcceptPayload,
  type OwnerTransferOfferPayload,
  ownerTransferAcceptPayloadFromCbor,
  ownerTransferOfferPayloadFromCbor,
  parseOwnerTransferAccept,
  parseOwnerTransferOffer,
  type SignedControlRecord,
  signControlRecord,
  verifyGenesis,
} from "./control.js";
export {
  type ControlSyncPlan,
  type LocalControl,
  localControlOf,
  planControlSync,
} from "./control-sync.js";
export {
  COSE_ALG_EDDSA,
  objectId,
  parseSignedObject,
  type SignedBytes,
  type SignedObject,
  type Signer,
  signObject,
  sigStructureBytes,
  type VerifyResult,
  verifySignedObject,
} from "./cose.js";
export {
  checkDataUnit,
  type DataProfileCodec,
  type DataUnitAadFields,
  type DataUnitCheck,
  type DataUnitCheckOptions,
  type DataUnitEquivocation,
  type DataUnitHoldReason,
  type DataUnitQuarantined,
  type DataUnitRejected,
  type DataUnitRejectReason,
  dataUnitAad,
  encodeDataUnitPayload,
  InMemorySeenUnits,
  type ReceiveDataUnitOptions,
  type ReceivedDataUnit,
  receiveDataUnit,
  type SealedDataUnit,
  type SeenRecord,
  type SeenUnits,
  sealDataUnit,
} from "./data-unit.js";
export {
  checkReceivedUrl,
  checkWriterUrl,
  ENDPOINT_FLAGS,
  type Endpoint,
  endpointFromCbor,
  endpointToCbor,
} from "./endpoint.js";
export {
  type ControlView,
  classifyDataUnit,
  type DataPutDecision,
  type DataUnitHeader,
  type EpochClassification,
  type EpochRotation,
  isSequenceWithinFrontier,
  KEY_EPOCH_REASON,
  rotateEpoch,
  serverAcceptsDataPut,
} from "./epoch.js";
export {
  type AuthenticatedSession,
  type AuthProofCheck,
  type AuthTranscriptFields,
  authTranscript,
  type ClientHandshakeConfig,
  type ClientSession,
  type ClientStep,
  clientReceive,
  decodeAuthTranscript,
  isResourceMessage,
  type RandomSource,
  type ReadySession,
  type ServerHandshakeConfig,
  type ServerSession,
  type ServerStep,
  selectWireProfile,
  serverReceive,
  signAuthProof,
  startClientHandshake,
  startServerSession,
  verifyAuthProof,
  WIRE_PROFILE,
} from "./handshake.js";
export {
  type ActorHave,
  type ActorRange,
  actorHaveFromCbor,
  actorHaveToCbor,
  addRange,
  addSequence,
  batchDataRanges,
  canonicalFrontierFromCbor,
  canonicalFrontierToCbor,
  checkLiveHave,
  type HaveVector,
  hasSequence,
  type LiveHaveEntry,
  liveHavesOf,
  MAX_DATA_GET_RANGES,
  missingAfter,
  missingFrom,
  normalizeLiveHaves,
  type SequenceRange,
  unionHaves,
} from "./have.js";
export {
  assembleInviteUri,
  decodeInviteSecret,
  encodeInviteSecret,
  INVITE_SECRET_VERSION,
  type Invitation,
  invitationPrincipal,
  parseInviteUri,
  verifyInvitationSecret,
} from "./invite.js";
export {
  type KeyPackageCheck,
  type KeyPackageRecipient,
  keyPackageHpkeAad,
  keyPackageHpkeInfo,
  openKeyPackage,
  type ReceivedKeyPackage,
  receiveKeyPackage,
  type SealedKeyPackage,
  sealKeyPackage,
  verifyKeyPackage,
} from "./key-package.js";
export {
  type AckBody,
  type AnyMessage,
  type AuthBody,
  type ChallengeBody,
  type ControlGetBody,
  type ControlHaveBody,
  type ControlHeadRef,
  type CoreMessageType,
  createMessage,
  type DataGetBody,
  type DataHaveBody,
  type DataRange,
  DEFAULT_MAX_MESSAGE_BYTES,
  type DecodedEnvelope,
  type DecodeOptions,
  decodeEnvelope,
  decodeFrame,
  decodeMessage,
  ERROR_CODE,
  type ErrorBody,
  type ExtensionMessage,
  encodeMessage,
  FIRST_EXTENSION_MESSAGE_TYPE,
  type Frame,
  type FrameResult,
  type HelloBody,
  type KeyPackageGetBody,
  type LfcpMessage,
  type LiveActorHave,
  MESSAGE_TYPE,
  type MessageBodies,
  messageErrorWireCode,
  newMessageId,
  type ObjectListBody,
  type PingBody,
  type PresenceBody,
  type PresenceLeaveBody,
  type ReadyBody,
  type ResourceBody,
  type ResourceHostBody,
  type ResourceHostedBody,
  type ResourceOpenBody,
  type ResourceOpenedBody,
  replyTo,
  type SnapshotBody,
  type SnapshotGetBody,
  type SnapshotSummary,
  type WireErrorName,
} from "./message.js";
export {
  CONTROL_TYPE,
  type ControlRecordPayload,
  controlRecordPayloadFromCbor,
  type DataUnitPayload,
  dataUnitPayloadFromCbor,
  decodeControlRecordPayload,
  decodeDataUnitPayload,
  decodeKeyPackagePayload,
  decodeSnapshotPayload,
  expectedSignerOf,
  type KeyPackagePayload,
  keyPackagePayloadFromCbor,
  type Parsed,
  parseControlRecord,
  parseDataUnit,
  parseKeyPackage,
  parseSnapshot,
  type SnapshotPayload,
  snapshotPayloadFromCbor,
} from "./objects.js";
export {
  decodePrincipalDescriptor,
  derivePrincipalId,
  encodePrincipalDescriptor,
  type PrincipalDescriptor,
  principalDescriptor,
  principalDescriptorFromCbor,
  principalDescriptorFromKeys,
  principalDescriptorToCbor,
} from "./principal.js";
export {
  type ClientConnectionEvent,
  type ClientConnectionState,
  clientConnectionTransition,
  type ServerSessionEvent,
  type ServerSessionState,
  serverSessionTransition,
} from "./session-state.js";
export {
  beyondCutoff,
  checkSnapshot,
  encodeSnapshotPayload,
  type ReceivedSnapshot,
  type ReceiveSnapshotOptions,
  receiveSnapshot,
  type SealedSnapshot,
  type SnapshotAadFields,
  type SnapshotCheck,
  type SnapshotCheckOptions,
  type SnapshotRejected,
  type SnapshotRejectReason,
  sealSnapshot,
  snapshotAad,
} from "./snapshot.js";
export {
  type ControlPutBody,
  controlPutBodyFromCbor,
  decodeControlPutBody,
  proposeControlPut,
  proposeControlTransition,
  type TransitionResult,
} from "./transition.js";
